/*
There will be a VAULT_DIR that can be configured (or placed in the environment).
This will be where all of the experiment data is stored. On Sherlock for example,
this would need to be stored in the scratch filesystem.

The organization is as follows:

VAULT_DIR/
|_ .vault - General metadata about the Vault binary, experiments etc.
|_ .vaultdb - A SQLite database file. This contains metadata about the vault instance.
|_ <experiment UUID>
  |_ user ingested data

Experiment directories:
root
|_ .vault - vault commands run by the experiment will be stored in a serialized format here.
|_ stuff generated by the experiment
 */

// Procedural macro imports.
#[macro_use]
extern crate diesel;
#[macro_use]
extern crate diesel_migrations;

mod cli;
mod vault;
use structopt::StructOpt;

fn main() {
    let args = cli::Commands::from_args();
    match vault::dispatch_command_line(args) {
        Ok(f) => println!("{}", f.to_string()),
        Err(e) => println!("Error: {}", e),
    }
}
